INSERT INTO ingredient ("name")
VALUES ('Salt'),
       ('Sugar'),
       ('Flour'),
       ('Butter'),
       ('Eggs'),
       ('Milk'),
       ('Baking Powder'),
       ('Vanilla Extract'),
       ('Cocoa Powder'),
       ('Olive Oil'),
       ('Garlic'),
       ('Onion'),
       ('Tomato'),
       ('Cheese'),
       ('Chicken'),
       ('Beef'),
       ('Pork'),
       ('Fish'),
       ('Carrot'),
       ('Potato'),
       ('Bell Pepper'),
       ('Broccoli'),
       ('Jackfruit'),
       ('Lettuce'),
       ('Cucumber'),
       ('Zucchini'),
       ('Mushroom'),
       ('Ginger'),
       ('Honey'),
       ('Maple Syrup'),
       ('Rice'),
       ('Pasta'),
       ('Oats'),
       ('Almonds'),
       ('Walnuts'),
       ('Peanuts'),
       ('Cashews'),
       ('Chili Powder'),
       ('Paprika'),
       ('Cinnamon'),
       ('Nutmeg'),
       ('Cloves'),
       ('Thyme'),
       ('Rosemary'),
       ('Basil'),
       ('Parsley'),
       ('Cilantro'),
       ('Mint'),
       ('Lemon'),
       ('Lime'),
       ('Orange'),
       ('Apple'),
       ('Banana'),
       ('Strawberry'),
       ('Blueberry'),
       ('Raspberry'),
       ('Blackberry'),
       ('Pineapple'),
       ('Mango'),
       ('Peach'),
       ('Pear'),
       ('Plum'),
       ('Grapes'),
       ('Watermelon'),
       ('Cantaloupe'),
       ('Spinach'),
       ('Kale'),
       ('Chard'),
       ('Eggplant'),
       ('Celery'),
       ('Leek'),
       ('Shallot'),
       ('Beetroot'),
       ('Cauliflower'),
       ('Asparagus'),
       ('Corn'),
       ('Green Beans'),
       ('Peas'),
       ('Chickpeas'),
       ('Lentils'),
       ('Quinoa'),
       ('Barley'),
       ('Oregano'),
       ('Dill'),
       ('Sage'),
       ('Bay Leaf'),
       ('Tarragon'),
       ('Fennel'),
       ('Mustard Seeds'),
       ('Soy Sauce'),
       ('Vinegar'),
       ('Yogurt'),
       ('Cream'),
       ('Coconut Milk'),
       ('Dark Chocolate'),
       ('White Chocolate'),
       ('Brown Sugar'),
       ('Molasses'),
       ('Cornstarch'),
       ('Gelatin'),
       ('Poppy Seeds'),
       ('Sesame Seeds'),
       ('Sunflower Seeds'),
       ('Pumpkin Seeds');